-- Passwords are now always generated by the server. An account whose password someone else chose
-- (a new clan head, a new member account, a reset) must set its own on the next sign-in.
-- Existing accounts keep working as they are.

-- AlterTable
ALTER TABLE `User` ADD COLUMN `mustChangePassword` BOOLEAN NOT NULL DEFAULT false;
